### ISSUE TITLE
bug on install on c5.8.1.0

### ISSUE THREAD

**Issue by zpartakov** [dausi/tds_z_i_p_gallery#1]
hello

great plugin which was missing for c5

I was quite excited to test it... 

but no install for me

on my prod server (ubuntu), after a while I have:
An unexpected error occurred.
An error occurred while processing this request.

if I allow c5 debug I have:
simplexml_load_file(): I/O warning : failed to load external entity "/web/www3/packages/tds_z_i_p_gallery/db.xml"
but... the file exists and my apache web server can read it

then I tried on my localhost:
Ubuntu 16.04.2 LTS
Apache/2.4.18
PHP version: 5.6.30-7+deb.sury.org~xenial+1
MySQL: 5.7.17-0ubuntu0.16.04.1

no error, everything seems ok 
but the editor is broken after the installation (I can open editing a zone, but no tools are anymore available)

if I uninstall the package, the WYSIWIG editor of c5 is back

did you really tested it on c5.8.1?

any clue?

if you need more info (logs etc.) don't hesitate to join me, fradeff@akademia.ch

Thank you & best regards

**Comment by tdausner** [comment]
Hello Fred,

yes, I did test the ZIP Image Gallery add-on on version 5.7.56 and 8.1.0. My [reference web site](http://tdsystem.eu) is running version 8.1.0, the add-on you'll find [here](http://tdsystem.eu/en/projects/concrete5/zip-image-gallery-for-concrete5) (click at "example").

Did you load the add-on from [git-hub](https://github.com/dausi/tds_z_i_p_gallery) or [concrete5 web site](http://www.concrete5.org/marketplace/addons/zip-image-gallery/)? Gitub version until now didn't keep the current version (V0.9.2), sorry (ran out of time...).

The error message you posted I haven't see yet. Looks like your c5 installation is broke. Can you please supply enviroment information (your-site/index.php/dashboard/system/environment/info)? Another (not too probable) cause could be an interference mismatch between add-ons.

cheers
Thomas

**Comment by zpartakov** [comment]
Hello Dausi

thank you for answering me

so, my first tests were made from github; same errors with [c5website](http://www.concrete5.org/marketplace/addons/zip-image-gallery/) but some improvement: on install I get with debug node the same message 

```
simplexml_load_file(): I/O warning : failed to load external entity "/web/www3/packages/tds_z_i_p_gallery/db.xml"
```

nevertheless, the package is installed, the editor is not broken anymore and it seems to work even if the mysql table is not installed: I may open the editor, upload a zip file and insert it and save the content block

but after publishing the page, when I click on the link with the inserted zip, I have this new message 

```
Error loading information from file </application/files/8614/9187/6434/desert.zip>
error
```
it doesn't seems to be linked with the zip as I tried with several zip - you may see some:
https://radeff.red/www3/application/files/8614/9187/6434/desert.zip
https://radeff.red/www3/application/files/2714/9187/6194/test.zip

so, I've tried to fix by creating the mysql table by hand, same error persists and the table remains empty

nothing in the logs (nor c5 nor apache)

don't spend to much time on this, it is quite possible, as you say, that my website has sthing wrong - I love to play with... and broke my c5.8 site, where I've made a lot of awful hand made packages!

but if you have any clue I'm quite interested because I'm a curious guy

otherwise I may try to install it on a fresh clean new c5.8 install

best regards

ps, as required:

my environment:
# concrete5 Version
Core Version - 8.1.0
Version Installed - 8.1.0
Database Version - 20170123000000

# concrete5 Packages
Add Multiple Pages (0.9.5), Community Store (1.0.8), Login Dialog (0.9.6), Neat (0.9.2), Stucco (2.0.0), Thumb Gallery (1.0.3), Whale Parallax Area (1.0.2), ZIP Gallery (0.9.4)

# concrete5 Overrides
languages/nb_NO/LC_MESSAGES/messages.mo, languages/nb_NO/LC_MESSAGES, languages/nb_NO, languages/ja_JP/LC_MESSAGES/messages.mo, languages/ja_JP/LC_MESSAGES, languages/ja_JP, languages/sv_SE/LC_MESSAGES/messages.mo, languages/sv_SE/LC_MESSAGES, languages/sv_SE, languages/de_DE/LC_MESSAGES/messages.mo, languages/de_DE/LC_MESSAGES, languages/de_DE, languages/es_PE/LC_MESSAGES/messages.mo, languages/es_PE/LC_MESSAGES, languages/es_PE, languages/it_IT/LC_MESSAGES/messages.mo, languages/it_IT/LC_MESSAGES, languages/it_IT, languages/en_GB/LC_MESSAGES/messages.mo, languages/en_GB/LC_MESSAGES, languages/en_GB, languages/nl_NL/LC_MESSAGES/messages.mo, languages/nl_NL/LC_MESSAGES, languages/nl_NL, languages/pt_BR/LC_MESSAGES/messages.mo, languages/pt_BR/LC_MESSAGES, languages/pt_BR, languages/es_PY/LC_MESSAGES/messages.mo, languages/es_PY/LC_MESSAGES, languages/es_PY, languages/el_GR/LC_MESSAGES/messages.mo, languages/el_GR/LC_MESSAGES, languages/el_GR, languages/cs_CZ/LC_MESSAGES/messages.mo, languages/cs_CZ/LC_MESSAGES, languages/cs_CZ, languages/ru_RU/LC_MESSAGES/messages.mo, languages/ru_RU/LC_MESSAGES, languages/ru_RU, languages/fi_FI/LC_MESSAGES/messages.mo, languages/fi_FI/LC_MESSAGES, languages/fi_FI, languages/da_DK/LC_MESSAGES/messages.mo, languages/da_DK/LC_MESSAGES, languages/da_DK, languages/fr_FR/LC_MESSAGES/messages.mo, languages/fr_FR/LC_MESSAGES/for_use_concrete5_core-dev-8_fr_FR.mo, languages/fr_FR/LC_MESSAGES/for_use_concrete5_core-dev-8_fr_FR.po, languages/fr_FR/LC_MESSAGES, languages/fr_FR, single_pages/dashboard/addtag.php, single_pages/dashboard/ebooksimport.php, single_pages/dashboard/addtag.php.201703091407, single_pages/dashboard, single_pages/kulturetrok/ebooks.php, single_pages/kulturetrok, languages/nb_NO/LC_MESSAGES/messages.mo, languages/nb_NO/LC_MESSAGES, languages/nb_NO, languages/ja_JP/LC_MESSAGES/messages.mo, languages/ja_JP/LC_MESSAGES, languages/ja_JP, languages/sv_SE/LC_MESSAGES/messages.mo, languages/sv_SE/LC_MESSAGES, languages/sv_SE, languages/de_DE/LC_MESSAGES/messages.mo, languages/de_DE/LC_MESSAGES, languages/de_DE, languages/es_PE/LC_MESSAGES/messages.mo, languages/es_PE/LC_MESSAGES, languages/es_PE, languages/it_IT/LC_MESSAGES/messages.mo, languages/it_IT/LC_MESSAGES, languages/it_IT, languages/en_GB/LC_MESSAGES/messages.mo, languages/en_GB/LC_MESSAGES, languages/en_GB, languages/nl_NL/LC_MESSAGES/messages.mo, languages/nl_NL/LC_MESSAGES, languages/nl_NL, languages/pt_BR/LC_MESSAGES/messages.mo, languages/pt_BR/LC_MESSAGES, languages/pt_BR, languages/es_PY/LC_MESSAGES/messages.mo, languages/es_PY/LC_MESSAGES, languages/es_PY, languages/el_GR/LC_MESSAGES/messages.mo, languages/el_GR/LC_MESSAGES, languages/el_GR, languages/cs_CZ/LC_MESSAGES/messages.mo, languages/cs_CZ/LC_MESSAGES, languages/cs_CZ, languages/ru_RU/LC_MESSAGES/messages.mo, languages/ru_RU/LC_MESSAGES, languages/ru_RU, languages/fi_FI/LC_MESSAGES/messages.mo, languages/fi_FI/LC_MESSAGES, languages/fi_FI, languages/da_DK/LC_MESSAGES/messages.mo, languages/da_DK/LC_MESSAGES, languages/da_DK, languages/fr_FR/LC_MESSAGES/messages.mo, languages/fr_FR/LC_MESSAGES/for_use_concrete5_core-dev-8_fr_FR.mo, languages/fr_FR/LC_MESSAGES/for_use_concrete5_core-dev-8_fr_FR.po, languages/fr_FR/LC_MESSAGES, languages/fr_FR, single_pages/dashboard/addtag.php, single_pages/dashboard/ebooksimport.php, single_pages/dashboard/addtag.php.201703091407, single_pages/dashboard, single_pages/kulturetrok/ebooks.php, single_pages/kulturetrok

# concrete5 Cache Settings
Block Cache - On
Overrides Cache - On
Full Page Caching - On - If blocks on the particular page allow it.
Full Page Cache Lifetime - Every 6 hours (default setting).

# Server Software
Apache

# Server API
fpm-fcgi

# PHP Version
5.6.22

# PHP Extensions
amf, bcmath, bz2, calendar, cgi-fcgi, Core, ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, http, iconv, id3, imap, intl, ionCube Loader, json, ldap, libxml, mailparse, mbstring, mcrypt, mhash, ming, mysql, mysqli, mysqlnd, OAuth, openssl, pcre, PDFlib, PDO, pdo_mysql, pdo_sqlite, pgsql, Phar, posix, propro, raphf, Reflection, session, SimpleXML, soap, SourceGuardian, SPL, SPPLUS, sqlite3, ssh2, standard, tidy, timezonedb, tokenizer, uploadprogress, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, yaz, Zend Guard Loader, zip, zlib

# PHP Settings
max_execution_time - 60
log_errors_max_len - 1024
max_file_uploads - 100
max_input_nesting_level - 64
max_input_time - 0
max_input_vars - 1000
memory_limit - 640M
post_max_size - 300M
sql.safe_mode - Off
upload_max_filesize - 300M
ldap.max_links - Unlimited
mysql.max_links - Unlimited
mysql.max_persistent - Unlimited
mysqli.max_links - Unlimited
mysqli.max_persistent - Unlimited
pcre.backtrack_limit - 1000000
pcre.recursion_limit - 100000
pgsql.max_links - Unlimited
pgsql.max_persistent - Unlimited
raphf.persistent_handle.limit - -1
session.cache_limiter - <i>no value</i>
session.gc_maxlifetime - 7200
soap.wsdl_cache_limit - 5

**Comment by tdausner** [comment]
Hello Fred,

when you face the error
```
Error loading information from file </application/files/8614/9187/6434/desert.zip>
error
```
can you plaes have a look in the network transfer? Enable the debugger in your browser (mostly by hitting F12) before you click at the ZIP Image Gallery link. When you get that error have a look at an entry in the network monitor named `getinfo?zip=/application/files/1814/9219/1678/desert.zip&tnw=50&tnh=50`. The response (JSON) should have more information. Please send me this.

cheers
Thomas

**Comment by zpartakov** [comment]
Hello Thomas

Thank you for the answer

Done as you suggested, you may see the result at:
https://radeff.red/tmp/snap2017-04-26_07-52-16.png

A 500... always terrible to understand for me! Checked in the apache logs but nothing

I've also tried to make a copy of the zip file which is located at https://radeff.red/tmp/testimages.zip and to change the source code of the content block, pointing to that url, same problem persists

As you may see testimages.zip seems valid and no svg images (which I know may cause trouble in c5.8.1)

Best Regards
Fred

**Comment by tdausner** [comment]
Hello Fred,

a 505 is really a horror. It lets harden my suspect of concrete5 setup mismatches.

To ensure it's neither a matter of ZIP Image Gallery software nor appache server setup please give the "pure" version from [https://github.com/dausi/zipgallery](https://github.com/dausi/zipgallery) a chance:
- file "swiper.html": set link to jquey lib in line 8
- file "swiper.html": set link to ZIP file in line 110.

If this works, its most probably a matter of your concrete5 installation :-(


cheers
Thomas

**Comment by zpartakov** [comment]
Hie Dausi
tested, 
https://radeff.red/zipgallery/swiper.html
not working, so may be it's on my apache... 
_Fehler beim Laden der Info aus Datei <//radeff.red/tmp/testimages.zip>
error_
I'll investigate and tell you

**Comment by tdausner** [comment]
Did you set up .htaccess according to your source directory?

Am 3. Mai 2017 15:59:23 MESZ schrieb Fred Radeff <notifications@github.com>:
>Hie Dausi
>tested, 
>https://radeff.red/zipgallery/swiper.html
>not working, so may be it's on my apache... 
>_Fehler beim Laden der Info aus Datei <//radeff.red/tmp/testimages.zip>
>error_
>I'll investigate and tell you
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/dausi/tds_z_i_p_gallery/issues/1#issuecomment-298919151

---
Thomas Dausner Binger Str. 65 56154 Boppard Germany mailto:thomas@dausner.de mobile: +49-151-59856154

**Comment by zpartakov** [comment]
yes done
